### ISSUE TITLE
the contract address is not displayed normally

### ISSUE THREAD

**Issue by wenchaopeng** [binance-chain/bsc-explorer#2]
Hi:
       I found a problem with the explorer of the bscscan testnet,the contract address is displayed as a personal address
pls check:
- https://testnet.bscscan.com/address/0xdc64fb863F9C00B110B5d8624Fa297921307B01F
- https://explorer.bitquery.io/bsc_testnet/smart_contract/0xdc64fb863f9c00b110b5d8624fa297921307b01f

**Comment by guagualvcha** [comment]
Hi, the issue is resolved now. Please check again. Thanks for reporting this.

**Comment by wenchaopeng** [comment]
ok，waiting for your good news，thanks

**Comment by guagualvcha** [comment]
resolved now, please double check

**Comment by wenchaopeng** [comment]
yes,resolved,but there is another issue,https://testnet.bscscan.com/address/0x19ad8594ad358cb00806b0880ac31676d9e27d37,this address is a token contract address,pls check

**Comment by wenchaopeng** [comment]
https://testnet.bscscan.com/token/0x19ad8594ad358cb00806b0880ac31676d9e27d37?a=0x0000000000000000000000000000000000000000  ,you can compare to this link

**Comment by guagualvcha** [comment]
It needs time to catch up with the latest height. Please check later

**Comment by wenchaopeng** [comment]
Do you mean that these two issues are the same issue. After the block synchronization is completed, it will be displayed normally?

**Comment by wenchaopeng** [comment]
I checked again,https://testnet.bscscan.com/token/0x19ad8594ad358cb00806b0880ac31676d9e27d37?a=0x0000000000000000000000000000000000000000 ,this link is displayed normally,thanks
